#pragma config(Motor,  port2,           leftMotor,     tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1 == 1){
		motor[leftMotor] = vexRT(Ch3);
		motor[rightMotor] = vexRT(Ch2);

	}

}
//Testing Github Sync
//Github Example
