#pragma config(Motor,  port2,           frontLeftMotor, tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           frontRightMotor, tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           backLeftMotor, tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           backRightMotor, tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat(forever){
	//Basic drive code
		while (1 == 1){
			motor[frontLeftMotor] = vexRT(Ch3);
			motor[backLeftMotor] = vexRT(Ch3);
			motor[frontRightMotor] = vexRT(Ch2);
			motor[backRightMotor] = vexRT(Ch2);
		}
	//Meccanum strafing code
		while (1 == 1){
			motor[frontLeftMotor] = 127;
	 		motor[backLeftMotor] = -127;
	 		motor[frontRightMotor] = 127;
	 		motor[backRightMotor] = -127;
	 	}
} // End repeat


}
